before_script:
  - env
stages:
  - build
  - cleanup_build
  - cleanup
  - deploy
Build Container:
  stage: build
  tags:
    - build
  script:
    - mkdir -p /tmp/ttrss
    - git clone --depth 1 https://tt-rss.org/gitlab/fox/tt-rss.git /tmp/ttrss/html
    - cp -r ${CI_PROJECT_DIR}/ttrss* /tmp/ttrss/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker build -t $CI_REGISTRY_IMAGE -f /tmp/ttrss/ttrss /tmp/ttrss
    - docker push $CI_REGISTRY_IMAGE
    - rm -rf /tmp/ttrss
    - docker rmi $CI_REGISTRY_IMAGE
cleanup_build_job:
  stage: cleanup
  tags:
    - build
  variables:
    GIT_STRATEGY: none
  script:
    - rm -rf /tmp/ttrss
  when: always
cleanup:
  stage: cleanup
  tags:
    - build
  variables:
    GIT_STRATEGY: none
  script:
    - docker system prune -a -f
Deploy Containers:
  stage: deploy
  environment: production
  tags:
    - kubectl
  script:
    - /opt/kubectl/kubectl --kubeconfig=$KUBECONFIG delete pods -l app=ttrss -n $KUBE_NAMESPACE
