before_script:
  - env
stages:
  - build
  - prepare
  - deploy_main
  - cleanup
Update Docker Images:
  stage: prepare
  script:
    - docker pull nginx
    - docker pull $CI_REGISTRY_IMAGE
Build Container:
  stage: build
  environment: build
  tags:
    - build
  script:
    - mkdir -p /tmp/ttrss
    - git clone --depth 1 https://tt-rss.org/gitlab/fox/tt-rss.git /tmp/ttrss/html
    - cp -r ${CI_PROJECT_DIR}/ttrss* /tmp/ttrss/
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker build -t $CI_REGISTRY_IMAGE -f /tmp/ttrss/ttrss /tmp/ttrss
    - docker push $CI_REGISTRY_IMAGE
    - docker rmi $(docker images -f "dangling=true" -q)
Deploy Containers:
  stage: deploy_main
  script:
    - docker stop ttrss
    - docker rm -v ttrss
    - docker stop nginx
    - docker rm -v nginx
    - /opt/muteweb/run_containers.sh
Remove Untagged:
  allow_failure: true
  stage: cleanup
  script:
    - docker rmi $(docker images -f "dangling=true" -q)

