before_script:
  - env
stages:
  - build
  - deploy
build:
  stage: build
  tags:
    - k8s
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination containers.internal/$CI_PROJECT_NAME:latest
Deploy Container:
  stage: deploy
  environment: production
  tags:
    - k8s
  image:
    name: alpine
  variables:
    GIT_STRATEGY: none
  script:
    - apk add -U openssl curl
    - curl -L -o /usr/bin/kubectl "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x /usr/bin/kubectl
    - kubectl version --client
    - kubectl --kubeconfig=$KUBECONFIG delete pods -l app=ttrss -n $KUBE_NAMESPACE

